#!/bin/bash
#SBATCH --time=0:50:00
#SBATCH --partition=regular
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=30
#SBATCH --profile=task


script_path=/home4/p307263/programs/scot_habrok/scot_habrok/s0_analysis_steps

# Parse command-line arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --args) ARGUMENT_STRING="$2"; shift ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

# Ensure the output directory exists
mkdir -p $OUTPUT_DIR
echo $OUTPUT_DIR
# THEN activate your specific environment load modules etc
bash $HOME/programs/hab_cli/hab_activate_dag_prfpy

# Check which Python is being used
echo "Using Python executable: $(which python)"
python -c "import sys; print('Python version:', sys.version)"

# Your script command
echo "Running main script"
python $script_path/HAB_G_fit.py $ARGUMENT_STRING
